<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyVersion>0.3.3</AssemblyVersion>
        <FileVersion>0.3.3</FileVersion>
        <InformationalVersion>0.3.3</InformationalVersion>

        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Version>0.3.3</Version>
        <PackageId>Kokoabim.CommandLineInterface</PackageId>
        <Description>Console tool command-line interface library.</Description>
        <TargetFramework>net10.0</TargetFramework>

        <PackageTags>console;cli;commandline;command-line;tool</PackageTags>
        <PackageVersion>0.3.4</PackageVersion>
        <PackageReleaseNotes></PackageReleaseNotes>

        <Authors>Spencer James</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/kokoabim/CommandLineInterface-DotNet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/kokoabim/CommandLineInterface-DotNet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

</Project>
