<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyVersion>0.2.0</AssemblyVersion>
        <FileVersion>0.2.0</FileVersion>
        <InformationalVersion>0.2.0</InformationalVersion>

        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Version>0.2.0</Version>
        <PackageId>Kokoabim.CommandLineInterface.AppHost</PackageId>
        <Description>AppHost support for Kokoabim.CommandLineInterface.</Description>
        <TargetFramework>net10.0</TargetFramework>

        <PackageVersion>0.3.0</PackageVersion>
        <PackageReleaseNotes>Initial release</PackageReleaseNotes>

        <Authors>Spencer James</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/kokoabim/CommandLineInterface-DotNet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/kokoabim/CommandLineInterface-DotNet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    </ItemGroup>

</Project>
